apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    name: order
spec:
  selector:
    matchLabels:
      name: order
  template:
    metadata:
      labels:
        name: order
    spec:
      containers:
        - name: order
          image: order
          imagePullPolicy: Never
          ports:
            - containerPort: 9001